names(subActFeatures_both)<-gsub("tBodyAcc-","Body acceleration signal in time domain (from the accelerometer)",names(subActFeatures_both))
names(subActFeatures_both)<-gsub("tBodyAccMag-","Body acceleration signal in time domain applied to Fast Fourier Transform(from the accelerometer)",names(subActFeatures_both))
names(subActFeatures_both)<-gsub("tBodyAccJerk-","Body acceleration jerk signal in time domain (from the accelerometer)",names(subActFeatures_both))
names(subActFeatures_both)<-gsub("tBodyAccJerkMag-","Body acceleration jerk signal in time domain applied to Fast Fourrier Transform (from the accelerometer)",names(subActFeatures_both))
names(subActFeatures_both)<-gsub("tGravityAcc-","Gravity acceleration signal in time domain (from the accelerometer)",names(subActFeatures_both))
names(subActFeatures_both)<-gsub("tGravityAccMag-","Gravity acceleration signal in time domain applied to Fast Fourier Transform(from the accelerometer)",names(subActFeatures_both))
names(subActFeatures_both)<-gsub("tBodyGyro-","Body acceleration signal in time domain (from the gyroscope)",names(subActFeatures_both))
names(subActFeatures_both)<-gsub("tBodyGyroMag-","Body acceleration signal in time domain applied to Fast Fourrier Transform(from the gyroscope)",names(subActFeatures_both))
names(subActFeatures_both)<-gsub("tBodyGyroJerk-","Body acceleration jerk signal in time domain (from the gyroscope)",names(subActFeatures_both))
names(subActFeatures_both)<-gsub("tBodyGyroJerkMag-","Body acceleration jerk signal in time domain applied to Fast Fourrier Transform(from the gyroscope)",names(subActFeatures_both))
names(subActFeatures_both)<-gsub("fBodyAcc-","Body acceleration signal in frequence domain (from the accelerometer)",names(subActFeatures_both))
names(subActFeatures_both)<-gsub("fBodyAccMag-","Body acceleration signal in frequence domain applied to Fast Fourier Transform(from the accelerometer)",names(subActFeatures_both))
names(subActFeatures_both)<-gsub("fBodyAccJerk-","Body acceleration jerk signal in frequence domain (from the accelerometer)",names(subActFeatures_both))
names(subActFeatures_both)<-gsub("fBodyGyro-","Body acceleration signal in frequence domain (from the gyroscope)",names(subActFeatures_both))
names(subActFeatures_both)<-gsub("fBodyAccJerkMag-","Body acceleration jerk signal in frequence domain applied to Fast Fourrier Transform (from the accelerometer)",names(subActFeatures_both))
names(subActFeatures_both)<-gsub("fBodyGyroMag-","Body acceleration signal in frequence domain applied to Fast Fourier Transform (from the gyroscope)",names(subActFeatures_both))